import { API, C, SEV_COLOR, timeAgo } from "../config";
import { useFetch } from "../hooks/useFetch";
import { SeverityBadge } from "../components/ui/SeverityBadge";

function downloadPDF(stats, alerts) {
  // Build a printable HTML and open in new tab for browser print-to-PDF
  const criticalCount = stats?.alerts_by_severity?.CRITICAL || 0;
  const topIp = stats?.top_attacking_ips?.[0];
  const critAlerts = (alerts?.alerts || []).filter(a => ["CRITICAL","HIGH"].includes(a.severity)).slice(0, 10);

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>SecureWatch Security Report — ${new Date().toLocaleDateString()}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #222; }
    h1 { color: #1a1a2e; border-bottom: 3px solid #00d4ff; padding-bottom: 10px; }
    h2 { color: #16213e; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th { background: #f0f4ff; padding: 10px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; }
    td { padding: 10px; border-bottom: 1px solid #e0e0e0; font-size: 13px; }
    .badge { padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }
    .critical { background: #ff174422; color: #ff1744; border: 1px solid #ff174455; }
    .high { background: #ff6d0022; color: #ff6d00; border: 1px solid #ff6d0055; }
    .medium { background: #ffd60022; color: #b8a000; border: 1px solid #ffd60055; }
    .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
    @media print { button { display: none; } }
  </style>
</head>
<body>
  <h1>🛡️ SecureWatch Security Report</h1>
  <p style="color:#666; font-size:13px">Generated: ${new Date().toLocaleString()} · Auto-generated by SecureWatch SIEM v2.0</p>

  <h2>Executive Summary</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Total Events (24h)</td><td><strong>${stats?.events_24h ?? "—"}</strong></td></tr>
    <tr><td>Active Alerts</td><td><strong>${stats?.active_alerts ?? "—"}</strong></td></tr>
    <tr><td>Critical Alerts</td><td><strong style="color:#ff1744">${criticalCount}</strong></td></tr>
    <tr><td>Top Attacking IP</td><td><strong style="color:#ff6d00; font-family:monospace">${topIp ? `${topIp.ip} (${topIp.count} events)` : "None"}</strong></td></tr>
    <tr><td>SSH Events</td><td>${stats?.events_by_source?.ssh ?? 0}</td></tr>
    <tr><td>Apache Events</td><td>${stats?.events_by_source?.apache ?? 0}</td></tr>
    <tr><td>Syslog Events</td><td>${stats?.events_by_source?.syslog ?? 0}</td></tr>
  </table>

  <h2>Recent Critical & High Alerts</h2>
  <table>
    <tr><th>Severity</th><th>Title</th><th>Rule</th><th>Events</th><th>Time</th></tr>
    ${critAlerts.map(a => `
    <tr>
      <td><span class="badge ${a.severity.toLowerCase()}">${a.severity}</span></td>
      <td>${a.title}</td>
      <td style="font-family:monospace; font-size:11px">${a.rule_name}</td>
      <td>${a.event_count}</td>
      <td>${new Date(a.created_at).toLocaleString()}</td>
    </tr>`).join("")}
  </table>

  <div class="footer">
    SecureWatch SIEM v2.0 · Confidential Security Report · ${new Date().toLocaleDateString()}
  </div>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const w = window.open("", "_blank");
  w.document.write(html);
  w.document.close();
}

export default function Reports() {
  const { data: stats }  = useFetch(`${API}/stats`);
  const { data: alerts } = useFetch(`${API}/alerts?limit=200`);
  const now = new Date().toLocaleString();

  const criticalCount = stats?.alerts_by_severity?.CRITICAL || 0;
  const topIp = stats?.top_attacking_ips?.[0];

  const rows = [
    ["Report Generated",    now],
    ["Total Events (24h)",  stats?.events_24h ?? "—"],
    ["Active Alerts",       stats?.active_alerts ?? "—"],
    ["Critical Alerts",     criticalCount],
    ["Top Attacking IP",    topIp ? `${topIp.ip} (${topIp.count} events)` : "None"],
    ["SSH Events",          stats?.events_by_source?.ssh ?? 0],
    ["Apache Events",       stats?.events_by_source?.apache ?? 0],
    ["Syslog Events",       stats?.events_by_source?.syslog ?? 0],
  ];

  const critAlerts = (alerts?.alerts || []).filter(a => ["CRITICAL","HIGH"].includes(a.severity)).slice(0, 8);

  return (
    <div>
      {/* Header card */}
      <div style={{
        background: C.card, border: `1px solid ${C.border}`,
        borderRadius: 12, padding: "20px 24px", marginBottom: 20,
        display: "flex", justifyContent: "space-between", alignItems: "center",
      }}>
        <div>
          <div style={{ color: C.accent, fontSize: 11, letterSpacing: 2, textTransform: "uppercase", fontFamily: "'Share Tech Mono', monospace", marginBottom: 4 }}>
            Security Report Summary
          </div>
          <div style={{ color: C.muted, fontSize: 12, fontFamily: "'Share Tech Mono', monospace" }}>
            Auto-generated · Refreshes every 10 seconds
          </div>
        </div>
        <button
          onClick={() => downloadPDF(stats, alerts)}
          style={{
            background: `linear-gradient(135deg, ${C.accent}22, ${C.purple}22)`,
            border: `1px solid ${C.accent}55`, color: C.accent,
            borderRadius: 8, padding: "8px 20px", cursor: "pointer",
            fontSize: 13, fontFamily: "'Share Tech Mono', monospace",
            display: "flex", alignItems: "center", gap: 8,
            transition: "all 0.2s",
          }}
          onMouseEnter={e => { e.currentTarget.style.background = `${C.accent}22`; e.currentTarget.style.boxShadow = `0 0 20px ${C.accent}33`; }}
          onMouseLeave={e => { e.currentTarget.style.background = `linear-gradient(135deg, ${C.accent}22, ${C.purple}22)`; e.currentTarget.style.boxShadow = "none"; }}
        >
          🖨️ Print / Export PDF
        </button>
      </div>

      {/* Stats grid */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 20 }}>
        {rows.map(([label, value]) => (
          <div key={label} style={{
            background: C.card, border: `1px solid ${C.border}`,
            borderRadius: 8, padding: "14px 18px",
            display: "flex", justifyContent: "space-between", alignItems: "center",
          }}>
            <span style={{ color: C.muted, fontSize: 13 }}>{label}</span>
            <span style={{ color: C.text, fontSize: 13, fontFamily: "'Share Tech Mono', monospace", fontWeight: 600 }}>
              {value}
            </span>
          </div>
        ))}
      </div>

      {/* Recent critical alerts */}
      <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 12, padding: 24 }}>
        <div style={{ color: C.red, fontSize: 11, letterSpacing: 2, textTransform: "uppercase", fontFamily: "'Share Tech Mono', monospace", marginBottom: 16 }}>
          🚨 Recent Critical & High Alerts
        </div>
        {critAlerts.length === 0 ? (
          <div style={{ color: C.muted, fontFamily: "'Share Tech Mono', monospace", fontSize: 13, textAlign: "center", padding: "20px 0" }}>
            ✅ No critical or high alerts
          </div>
        ) : critAlerts.map(a => (
          <div key={a.id} style={{ display: "flex", gap: 12, padding: "10px 0", borderBottom: `1px solid ${C.border}`, alignItems: "center" }}>
            <SeverityBadge sev={a.severity} />
            <span style={{ flex: 1, fontSize: 13, color: C.text }}>{a.title}</span>
            <span style={{ fontSize: 11, color: C.purple, fontFamily: "'Share Tech Mono', monospace" }}>{a.rule_name}</span>
            <span style={{ fontSize: 11, color: C.muted, fontFamily: "'Share Tech Mono', monospace" }}>{timeAgo(a.created_at)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
